"""
===============================================================================
MODULE: app/schemas/government_rag.py
===============================================================================
PURPOSE:
    Defines data models for Phase 6D (Grounded RAG + Explainable Government Guidance).

WHAT IT DOES:
    - Defines GovernmentRAGSource dataclass representing an official government citation.
    - Defines GovernmentRAGResponse dataclass container for grounded RAG answer responses.

WHY WE NEED IT:
    Downstream users (government procurement officers) need transparent, grounded answers
    that explicitly cite official government sources (Document, Page Number, Section Name, Quote, Similarity Score).
    These models enforce that every answer is backed by verifiable source citations.

HOW IT FITS INTO RAG:
    User Question -> Phase 6C Retrieval -> Phase 6D Grounded RAG -> GovernmentRAGResponse
    -> Grounded Answer View in UI / CLI
===============================================================================
"""

# standard library imports
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional


@dataclass
class GovernmentRAGSource:
    """
    Data model representing an official government source citation bound to a RAG answer.

    FIELDS EXPLAINED:
        chunk_id: Validated chunk identifier (e.g. "GOV-001-CH-002").
        document_id: Identifier of the parent document (e.g. "GOV-001").
        document_name: Filename of the source government PDF (e.g. "procurement_guidelines.pdf").
        page_number: 1-based page number where the text originated.
        section_name: Heading title of the section if detected, or None.
        similarity_score: Cosine similarity score between query and retrieved chunk (0.0 to 1.0).
        quoted_text: Exact text quote from the retrieved government document chunk.
    """
    chunk_id: str
    document_id: str
    document_name: str
    page_number: int
    similarity_score: float
    quoted_text: str
    section_name: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Converts source citation instance to dictionary."""
        return asdict(self)


@dataclass
class GovernmentRAGResponse:
    """
    Data model representing a grounded RAG response to a procurement question.

    FIELDS EXPLAINED:
        query: Original input question or procurement requirement text.
        answer: Concise, factual, source-grounded answer generated by LLM.
        status: Execution status string:
                "SUCCESS" -> Answer generated and backed by validated citations.
                "INSUFFICIENT_GOVERNMENT_EVIDENCE" -> Zero or weak evidence retrieved; LLM not called.
                "CITATION_VALIDATION_ERROR" -> LLM cited an unknown chunk_id not present in context.
                "GENERATION_FAILED" -> LLM generation or JSON parsing failed.
                "RETRIEVAL_FAILED" -> Phase 6C retrieval failed.
                "VALIDATION_ERROR" -> Input query was empty or whitespace.
        grounding_status: Grounding state string:
                          "GROUNDED" -> Answer strictly grounded in retrieved evidence.
                          "INSUFFICIENT_EVIDENCE" -> Insufficient evidence retrieved.
                          "RETRIEVAL_FAILED" -> Retrieval error occurred.
                          "GENERATION_FAILED" -> Generation or citation validation error.
        retrieval_count: Count of retrieved government knowledge chunks evaluated.
        confidence: Optional confidence rating (or None).
        error_message: Error details if status is not "SUCCESS", or None.
        sources: List of GovernmentRAGSource objects containing official citations.
    """
    query: str
    answer: str
    status: str = "SUCCESS"
    grounding_status: str = "GROUNDED"
    retrieval_count: int = 0
    confidence: Optional[float] = None
    error_message: Optional[str] = None
    sources: List[GovernmentRAGSource] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Serializes response object and nested sources into dictionary."""
        return {
            "query": self.query,
            "answer": self.answer,
            "status": self.status,
            "grounding_status": self.grounding_status,
            "retrieval_count": self.retrieval_count,
            "confidence": self.confidence,
            "error_message": self.error_message,
            "sources": [s.to_dict() for s in self.sources],
        }
